---
namespace: almaops
name: monitoring
version: 1.0.15
readme: README.md
authors:
  - Valentin Gostev <val@le.lc>
description: 'This Ansible collection provides roles for deploying your monitoring stack'
license:
  - MIT
tags:
  - monitoring
  - grafana
dependencies:
  almaops.common: '>=1.0.6'
  community.grafana: '>=1.4.0'
repository: 'https://github.com/almaops/ansible-collection-monitoring'
homepage: 'https://almaops.com'
issues: 'https://github.com/almaops/ansible-collection-monitoring/issues'
build_ignore:
  - .gitignore
  - .yamllint
...
