namespace: almaops
name: monitoring
version: 1.0.20
readme: README.md
authors:
  - Valentin Gostev <val@le.lc>
description: >-
  This Ansible collection provides roles and playbooks for deploying your
  monitoring stack
license:
  - MIT
tags:
  - monitoring
  - grafana
  - prometheus
  - loki
dependencies:
  almaops.common: '>=1.0.6'
  community.grafana: '>=1.4.0'
  prometheus.prometheus: '>=0.17.0'
  community.docker: '>=4.0.0'
repository: 'https://github.com/almaops/ansible-collection-monitoring'
homepage: 'https://almaops.com'
issues: 'https://github.com/almaops/ansible-collection-monitoring/issues'
build_ignore:
  - .gitignore
  - .yamllint
  - .github
