---
argument_specs:
  main:
    short_description: Ensure default admin credentials are set
    options:
      ct_grafana_env_admin_user:
        type: "string"
        required: true
        description: "Default Grafana's admin username"
      ct_grafana_env_admin_password:
        type: "string"
        required: true
        description: "Default Grafana's admin password"
...
