---
- name: "{{ ct_grafana_task_prefix }} Create grafana group"
  ansible.builtin.group:
    name: "{{ ct_grafana_user_group }}"
    state: present
    gid: "{{ ct_grafana_user_gid }}"

- name: "{{ ct_grafana_task_prefix }} Create grafana user"
  ansible.builtin.user:
    name: "{{ ct_grafana_user_name }}"
    system: true
    shell: /bin/false
    group: "{{ ct_grafana_user_group }}"
    uid: "{{ ct_grafana_user_uid }}"

- name: "{{ ct_grafana_task_prefix }} Create base directories"
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    owner: root
    group: root
    mode: '0755'
  loop:
    - "{{ ct_grafana_path_config_base }}"
    - "{{ ct_grafana_path_data_base }}"

- name: "{{ ct_grafana_task_prefix }} Create env file"
  ansible.builtin.template:
    src: "{{ ct_grafana_template_env }}"
    dest: "{{ ct_grafana_path_config_env }}"
    owner: root
    group: root
    mode: '0755'

- name: "{{ ct_grafana_task_prefix }} Create data directory"
  ansible.builtin.file:
    state: directory
    path: "{{ ct_grafana_path_data_volume }}"
    owner: "{{ ct_grafana_user_name }}"
    group: "{{ ct_grafana_user_group }}"
    mode: '0755'

- name: "{{ ct_grafana_task_prefix }} Un-mount provisioning directory"
  ansible.builtin.set_fact:
    _ct_grafana_ct_volumes_provisioning: []
  when: not ct_grafana_enable_provisioning

- name: "{{ ct_grafana_task_prefix }} Provisioning"
  ansible.builtin.include_tasks: provisioning.yml
  when: ct_grafana_enable_provisioning

- name: "{{ ct_grafana_task_prefix }} Un-mount LDAP config"
  ansible.builtin.set_fact:
    _ct_grafana_ct_volumes_ldap_config: []
  when: not ct_grafana_enable_ldap

- name: "{{ ct_grafana_task_prefix }} LDAP Integration"
  ansible.builtin.include_tasks: ldap.yml
  when: ct_grafana_enable_ldap

- name: "{{ ct_grafana_task_prefix }} Persist data volume?"
  ansible.builtin.set_fact:
    _ct_grafana_ct_volumes: "{{ ct_grafana_enable_data_persistence | ternary(ct_grafana_ct_volumes, []) }}"

- name: "{{ ct_grafana_task_prefix }} Create container"
  community.docker.docker_container:
    name: "{{ ct_grafana_ct_name }}"
    image: "{{ ct_grafana_ct_image }}"
    state: "{{ ct_grafana_ct_state }}"
    restart_policy: "{{ ct_grafana_ct_restart_policy }}"
    restart: "{{ ct_grafana_ct_restart }}"
    pull: "{{ ct_grafana_ct_pull }}"
    ports: "{{ ct_grafana_enable_ports | ternary(ct_grafana_ct_ports, omit) }}"
    volumes: "{{ _ct_grafana_ct_volumes + _ct_grafana_ct_volumes_provisioning + _ct_grafana_ct_volumes_ldap_config }}"
    user: "{{ ct_grafana_ct_user }}"
    recreate: "{{ ct_grafana_ct_recreate }}"
    env_file: "{{ ct_grafana_path_config_env }}"
...
