---
galaxy_info:
  author: Valentin Gostev
  description: Ansible role deploys Grafana Loki container
  company: AlmaOps
  role_name: ct_loki
  namespace: almaops
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions: all
    - name: Debian
      versions: all
  galaxy_tags:
    - grafana
    - loki
    - logging
dependencies: []
...
